### ISSUE TITLE
autogen.sh give error

### ISSUE THREAD

**Issue by noureddin212** [DNS-OARC/dnsmeter#18]
Hello 
When I launch ./autogen.sh
 it generate an error :
./autogen.sh: 21: ./autogen.sh: autoreconf: not found

I do not see autoreconf in the directory 
Can you please help ?
Regards

**Comment by jelu** [comment]
You need to have a C++ development environment installed:

> dnsmeter requires a couple of libraries beside a normal C++ compiling environment with autoconf, automake and libtool.

What distribution are you using?

**Comment by jelu** [comment]
Closing because of no response.
