### ISSUE TITLE
dnsmeter payload file issue

### ISSUE THREAD

**Issue by bogdan-dukic** [DNS-OARC/dnsmeter#35]
Dear dns-oarc admin,

I have installed dnsmeter 1.0.2 coupla of days ago on Ubuntu 20.04.
But i did not manage to start it.

Plese see what i get.

```
ogdan@bogdan-HP-EliteBook-840-G3:~$ sudo dnsmeter -p /home/bogdan/allot_dns_thq_pe2_02032023_1335.pcap -r 1000 -s pcap -z [109.245.224.102:53](http://109.245.224.102:53/) -c /home/bogdan/results_dns_meter.txt --ignore
INFO: Loading and precompile payload. This could take some time...
Packets read from pcap file: 1690986, valid UDP DNS queries: 0
ERROR: could not open payload file or it does not contain any queries
Exception: InvalidQueryFile [No valid Queries found in pcap file [/home/bogdan/allot_dns_thq_pe2_02032023_1335.pcap]]
bogdan@bogdan-HP-EliteBook-840-G3:~$
```

It looks like there are not DNS queries in the payload file, but there are a lot of DNS queries

Please advise what to do.

Thank you and best regards,
Bogdan

**Comment by jelu** [comment]
It looks like you need to prepare the PCAP for it to work for `dnsmeter`, try:
```
tcpdump -r /home/bogdan/allot_dns_thq_pe2_02032023_1335.pcap -w /home/bogdan/prepared.pcap ip and udp port 53
```

And then use `/home/bogdan/prepared.pcap`.

**Comment by bogdan-dukic** [comment]
Thank you Jerry,

First, Thank you for your response.
I did what you recommended, but the same result.

***@***.***:~$ sudo tcpdump -r
/home/bogdan/allot_dns_thq_pe2_02032023_1335.pcap -w
/home/bogdan/prepared.pcap ip and udp port 53
reading from file /home/bogdan/allot_dns_thq_pe2_02032023_1335.pcap,
link-type EN10MB (Ethernet)

***@***.***:~$ ls -l *.pcap
-rwxrwxrwx 1 bogdan  bogdan  256628746 мар  2 15:03
allot_dns_thq_pe2_02032023_1335.pcap
-rwxrwxrwx 1 root    root     96369856 мар  7 15:44 dns_queries.pcap
-rw-r--r-- 1 tcpdump tcpdump        24 мар 13 09:55 prepared.pcap
-rw------- 1 root    root         2064 мар  7 16:07 proba.pcap

***@***.***:~$ sudo dnsmeter -p
/home/bogdan/prepared.pcap -r 1000 -s pcap -z 109.245.224.102:53 -c
/home/results_dns_meter.txt --ignore
INFO: Loading and precompile payload. This could take some time...
Packets read from pcap file: 0, valid UDP DNS queries: 0
ERROR: could not open payload file or it does not contain any queries
Exception: InvalidQueryFile [No valid Queries found in pcap file
[/home/bogdan/prepared.pcap]]
***@***.***:~$


Also I did it with another PCAP file (attached) and the result is little
bit different (bolded).

***@***.***:~$ sudo dnsmeter -p
/home/bogdan/proba.pcap -r 1000 -s pcap -z 109.245.224.102:53 -c
/home/bogdan/results_dns_meter.txt --ignore
INFO: Loading and precompile payload. This could take some time...
ERROR: could not open payload file or it does not contain any queries
*Exception: InvalidQueryFile [No valid Queries found in Queryfile]*
***@***.***:~$

It looks like proba.pcap is not recognized as pcap file.

Best regards,
Bogdan


пет, 10. мар 2023. у 09:36 Jerry Lundström ***@***.***> је
написао/ла:

**Comment by bogdan-dukic** [comment]
Hi Jerry,

That's right.

Since original file /home/bogdan/allot_dns_thq_pe2_0203202/3_1335.pcap is
too big to be sent by email, I extracted the first 100 packets into file
/home/bogdan/allot_partial.pcap.
It consists of dns queries and responses only.

The result of dnsmeter is the same

***@***.***:~$ sudo dnsmeter -p
/home/bogdan/allot_partial.pcap -r 1000 -s pcap -z 109.245.224.102:53 -c
/home/results_dns_meter.txt --ignore
INFO: Loading and precompile payload. This could take some time...
Packets read from pcap file: 100, valid UDP DNS queries: 0
ERROR: could not open payload file or it does not contain any queries
Exception: InvalidQueryFile [No valid Queries found in pcap file
[/home/bogdan/allot_partial.pcap]]
***@***.***:~$

Pcap file is attached. I think it is a regular pcap file since it can be
opened by wireshark.


Best regards,
Bogdan



пон, 13. мар 2023. у 10:15 Jerry Lundström ***@***.***> је
написао/ла:

**Comment by jelu** [comment]
You CAN'T attach files in emails to GitHub.

Use GitHub website!

**Comment by bogdan-dukic** [comment]
File attached
[allot_partial.pcap.gz](https://github.com/DNS-OARC/dnsmeter/files/10956080/allot_partial.pcap.gz)

**Comment by jelu** [comment]
All packets in your files are VLAN'ed, `dnsmeter` can't read that.

```
tcpdump -envr allot_partial.pcap 
reading from file allot_partial.pcap, link-type EN10MB (Ethernet)
13:35:20.788698 20:e0:9c:47:cd:4a > b4:96:91:d8:57:f4, ethertype 802.1Q (0x8100), length 78: vlan 1287, p 0, ethertype IPv4, (tos 0x28, ttl 58, id 16583, offset 0, flags [DF], proto UDP (17), length 60)
    10.38.51.189.21964 > 109.245.224.103.53: 50935+ A? gum.criteo.com. (32)
```

You'll have to extract/remove the VLAN tagging from the PCAP so that you see the packets using this command:

```
$ tcpdump -envr allot_partial.pcap ip and udp port 53
```

**Comment by bogdan-dukic** [comment]
I made another pcap file with no VLAN tags and with just a few queries (attached).

And this is result.

bogdan@bogdan-HP-EliteBook-840-G3:~$ sudo dnsmeter -p /home/bogdan/simple_dns_pcap.pcap -r 1000 -s pcap -z 109.245.224.102:53 -c /home/results_dns_meter.txt --ignore
INFO: Loading and precompile payload. This could take some time...
ERROR: could not open payload file or it does not contain any queries
Exception: InvalidQueryFile [No valid Queries found in Queryfile]
bogdan@bogdan-HP-EliteBook-840-G3:~$

[simple_dns_pcap.pcap.gz](https://github.com/DNS-OARC/dnsmeter/files/10956489/simple_dns_pcap.pcap.gz)

Best regards,
Bogdan

**Comment by jelu** [comment]
I donno why this doesn't work directly with that PCAP, I don't see anything wrong with it.

But if I filtered it with `tcpdump`, I could get it say valid queries.

Try:
```
tcpdump -r simple_dns_pcap.pcap -w simple_dns_pcap_filtered.pcap dst port 53
```

And then use that file for `dnsmeter`.

**Comment by bogdan-dukic** [comment]
Thank you Jerry,

It works.

Just to sumarize.

1. PCAP file should contains ONLY DNS queries
2. VLAN tags if any should be removed from packets. Command is tcprewrite --enet-vlan=del --infile=input.pcap --outfile=output.pcap

Best regards,
Bogdan

**Comment by jelu** [comment]
> PCAP file should contains ONLY DNS queries

Actually no. I got other PCAP files with queries and responses and it found valid queries in those.

**Comment by jelu** [comment]
Closing since filtering PCAP worked.
