### ISSUE TITLE
[BUG] bad udp checksum on Ubuntu22.04

### ISSUE THREAD

**Issue by hi-glenn** [DNS-OARC/dnsmeter#39]
The packet capture on the remote machine shows a bad checksum

**Comment by jelu** [comment]
This is very likely a false-positive as checksum are recalculated and you do not specify what says "bad checksum".

If you still feel this is an issue then you need to provide a lot more information about how you are running `dnsmeter`, full console/syslog outputs and where/what says bad checksum. Once you've added that you can reopen.

**Comment by hi-glenn** [comment]
On the remote server, the tcpdump capture shows "UDP bad checksum".

The issue with dnsmeter v1.0.2  is deployed on Ubuntu 22.04, and the same problem occurs on Ubuntu 24.04


![bad-checksum-2](https://github.com/user-attachments/assets/407bea90-c5f8-4790-858c-83c7ce4499ee)

**Comment by jelu** [comment]
This is very likely the case of checksum calculation being offloaded onto the NIC, nothing to do with dnsmeter.
